AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-fcm-worker

  Sample SAM Template for sam-fcm-worker

Parameters:
  Stage:
    Type: String
    Default: staging
    AllowedValues:
      - staging
      - product

Mappings:
  Configs:
    staging:
      RedisSecretName: fcm-worker-staging-redis
      QueueName: fcm-main-queue-staging-sqs
    product:
      RedisSecretName: fcm-worker-product-redis
      QueueName: fcm-main-queue-product-sqs

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
    Runtime: nodejs24.x
    Architectures:
      - x86_64

Resources:
  FCMMainQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !FindInMap [ Configs, !Ref Stage, QueueName ]
      VisibilityTimeout: 60
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt FCMDeadLetterQueue.Arn
        maxReceiveCount: 5

  FCMDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub
        - '${BaseName}-dlq'
        - BaseName: !FindInMap [ Configs, !Ref Stage, QueueName ]
      MessageRetentionPeriod: 1209600

  FCMWorker:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: fcm-worker
      CodeUri: fcm-worker
      Handler: app.lambdaHandler
      Environment:
        Variables:
          Stage: !Ref Stage
          REDIS_URL: !Sub
            - '{{resolve:secretsmanager:${SecretName}:SecretString:REDIS_URL}}'
            - { SecretName: !FindInMap [ Configs, !Ref Stage, RedisSecretName ] }
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt FCMMainQueue.Arn
            BatchSize: 1
            MaximumBatchingWindowInSeconds: 0
            ScalingConfig:
              MaximumConcurrency: 10
            Enabled: true
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - app.ts