AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-fcm-worker

  Sample SAM Template for sam-fcm-worker

Parameters:
  Stage:
    Type: String
    Default: staging
    AllowedValues:
      - staging
      - product

Mappings:
  Configs:
    staging:
      SecretName: fcm-worker-redis-staging
      QueueName: fcm-main-queue-sqs
      SubnetIds: "subnet-0dfc81faba494ecd0,subnet-0e1347a5c00994b52"
      SecurityGroupIds: "sg-078527d451f97cd7e"
    product:
      SecretName: fcm-worker-redis-prod
      QueueName: fcm-main-queue-sqs
      SubnetIds: []
      SecurityGroupIds: []

Globals:
  Function:
    Timeout: 60
    MemorySize: 512
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
    Runtime: nodejs24.x
    Architectures:
      - x86_64

Resources:
  FCMMainQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub
        - '${BaseName}-${State}'
        - BaseName: !FindInMap [ Configs, !Ref Stage, QueueName ]
          State: !Ref Stage
      VisibilityTimeout: 60
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt FCMDeadLetterQueue.Arn
        maxReceiveCount: 5

  FCMDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub
        - '${BaseName}-dlq-${State}'
        - BaseName: !FindInMap [ Configs, !Ref Stage, QueueName ]
          State: !Ref Stage
      MessageRetentionPeriod: 1209600

  FCMWorkerLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub
        - '/aws/lambda/${BaseName}-${State}'
        - BaseName: !FindInMap [ Configs, !Ref Stage, QueueName ]
          State: !Ref Stage
      RetentionInDays: 30

  FCMWorker:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub
        - '${BaseName}-${State}'
        - BaseName: !FindInMap [ Configs, !Ref Stage, QueueName ]
          State: !Ref Stage
      CodeUri: fcm-worker
      Handler: app.lambdaHandler
      Environment:
        Variables:
          Stage: !Ref Stage
          REDIS_URL: !Sub
            - '{{resolve:secretsmanager:${SecretName}:SecretString:REDIS_URL}}'
            - { SecretName: !FindInMap [ Configs, !Ref Stage, SecretName ] }
      VpcConfig:
        SubnetIds: !Split [ ",", !FindInMap [ Configs, !Ref Stage, SubnetIds ] ]
        SecurityGroupIds: !Split [ ",", !FindInMap [ Configs, !Ref Stage, SecurityGroupIds ] ]
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt FCMMainQueue.Arn
            BatchSize: 1
            MaximumBatchingWindowInSeconds: 0
            ScalingConfig:
              MaximumConcurrency: 10
            Enabled: true
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - app.ts